{
 "title": "Hyperliquid Node Operator Monitor Copy",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "commit",
    "query": {
     "query": "label_values(hl_visor_version_info,commit)"
    }
   },
   {
    "name": "commit_date",
    "label": "Commit date",
    "query": {
     "query": "label_values(hl_visor_version_info,date)"
    }
   },
   {
    "name": "validator_address",
    "label": "Validator Address",
    "query": {
     "query": "label_values(hl_validator_info_info,address)"
    }
   },
   {
    "name": "validator_name",
    "label": "validator Name",
    "query": {
     "query": "label_values(hl_validator_info_info,name)"
    }
   },
   {
    "name": "node_commit_date",
    "label": "Node Commit date",
    "query": {
     "query": "label_values(hl_node_version_info_info,date)"
    }
   },
   {
    "name": "node_commit",
    "label": "Node Commit",
    "query": {
     "query": "label_values(hl_node_version_info_info,commit)"
    }
   },
   {
    "name": "latest_commit_date",
    "label": "Latest Commit date",
    "query": {
     "query": "label_values(hl_visor_latest_version_info_info,date)"
    }
   },
   {
    "name": "latest_commit",
    "label": "Latest Commit",
    "query": {
     "query": "label_values(hl_visor_latest_version_info_info,commit)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"color: #00FF00; font-size: 24px; font-weight: bold; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <strong>$validator_name: $validator_address</span>\n</div>\n"
   }
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_validator_jailed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recent Block Proposed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_validator_recent_blocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_validator_stake/100000", "legendFormat": "__auto" }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_node_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Oldest Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_oldest_block_data_age", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": {
    "defaults": {
     "unit": "Date & Time | YYYY-MM-DD HH:mm:ss"
    }
   },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_latest_block_time", "legendFormat": "__auto" }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "RAM Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_disk_usage", "legendFormat": "__auto" }
   ]
  },
  { "title": "CLIENT INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Current Node binary version",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "options": {
    "content": "<!-- <div style=\"background-color: #222; padding: 15px; border-radius: 10px; color: #00FF00; font-size: 24px; font-weight: bold; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <strong>Commit Hash:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit</span><br/>\n  <strong>Date:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit_date</span>\n</div> -->\n\n<div style=\"padding: 5px; border-radius: 10px;\">\n  <span style=\"font-size: 14px; color: #FFDD44;\">$node_commit</span><br/>\n  <span style=\"font-size: 14px; color: #FFDD44;\">$node_commit_date</span>\n</div>\n"
   }
  },
  {
   "title": "Current Node binary up-to-date status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hl_node_up_to_date" }
   ]
  },
  {
   "title": "Latest Visor binary version",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "options": {
    "content": "<!-- <div style=\"background-color: #222; padding: 15px; border-radius: 10px; color: #00FF00; font-size: 24px; font-weight: bold; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <strong>Commit Hash:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit</span><br/>\n  <strong>Date:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit_date</span>\n</div> -->\n\n<div style=\"padding: 5px; border-radius: 10px;\">\n  <span style=\"font-size: 14px; color: #FFDD44;\">$latest_commit</span><br/>\n  <span style=\"font-size: 14px; color: #FFDD44;\">$latest_commit_date</span>\n</div>\n"
   }
  },
  {
   "title": "Current Visor binary version",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
   "options": {
    "content": "<!-- <div style=\"background-color: #222; padding: 15px; border-radius: 10px; color: #00FF00; font-size: 24px; font-weight: bold; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <strong>Commit Hash:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit</span><br/>\n  <strong>Date:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit_date</span>\n</div> -->\n\n<div style=\"padding: 5px; border-radius: 10px;\">\n  <span style=\"font-size: 14px; color: #FFDD44;\">$commit</span><br/>\n  <span style=\"font-size: 14px; color: #FFDD44;\">$commit_date</span>\n</div>\n"
   }
  },
  {
   "title": "Current Visor binary up-to-date status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hl_visor_software_up_to_date" }
   ]
  },
  { "title": "CONSENSUS METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Validator Jailed Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 24 },
   "targets": [
    { "expr": "hl_validator_jailed_status" }
   ]
  },
  {
   "title": "Jailed Validators Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(hl_validator_jailed_status)"
    }
   ]
  },
  {
   "title": "Validator Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_validator_count", "legendFormat": "Validator Count" }
   ]
  },
  {
   "title": "Validator Jailings Timeseries",
   "type": "timeseries",
   "description": "1 = jailed\n0 = not jailed",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hl_validator_jailed_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Proposals Per Second (15m basis)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(hl_proposer_count_total[15m])",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  {
   "title": "Validator Proposal Share (4h basis)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (proposer) (increase(hl_proposer_count_total[4h]))\n/\nscalar(sum(increase(hl_proposer_count_total[4h])))\n* 100\n",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  { "title": "BLOCK METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Block Height ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hl_block_height", "legendFormat": "block_height" }
   ]
  },
  {
   "title": "Block Time Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "300 / delta(hl_block_height[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "900 / delta(hl_block_height[15m])",
     "legendFormat": "15m"
    },
    {
     "expr": "3600 / delta(hl_block_height[1h])",
     "legendFormat": "1h"
    },
    {
     "expr": "14400 / delta(hl_block_height[4h])",
     "legendFormat": "4h"
    },
    {
     "expr": "43200 / delta(hl_block_height[12h])",
     "legendFormat": "12h"
    },
    {
     "expr": "86400 / delta(hl_block_height[24h])",
     "legendFormat": "24h"
    }
   ]
  },
  {
   "title": "Block Apply Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    { "expr": "hl_apply_duration", "legendFormat": "apply_duration" }
   ]
  }
 ]
}